/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kasirpro;

/**
 *
 * @author M. Aziz Ridwan
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        tampil_total_Makanan();
        tampil_total_Minuman();
        tampil_total_Paket();

    }

    void tampil_total_Makanan() {
        try {
            String sql = "SELECT COUNT(*) AS total FROM makanan";
            java.sql.Connection conn = Koneksi.ConfigDB();
            java.sql.PreparedStatement statement = conn.prepareStatement(sql);

            java.sql.ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                totalM.setText(resultSet.getString("total"));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    void tampil_total_Minuman() {
        try {
            String sql = "SELECT COUNT(*) AS total FROM minuman";
            java.sql.Connection conn = Koneksi.ConfigDB();
            java.sql.PreparedStatement statement = conn.prepareStatement(sql);

            java.sql.ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
            totalMN.setText(resultSet.getString("total"));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    void tampil_total_Paket() {
        try {
            String sql = "SELECT COUNT(*) AS total FROM paket";
            java.sql.Connection conn = Koneksi.ConfigDB();
            java.sql.PreparedStatement statement = conn.prepareStatement(sql);

            java.sql.ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                totalPK.setText(resultSet.getString("total"));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanelGradient1 = new jpanelgradient.JPanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalPK = new javax.swing.JLabel();
        totalM = new javax.swing.JLabel();
        totalMN = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelGradient2 = new jpanelgradient.JPanelGradient();
        jLabel22 = new javax.swing.JLabel();
        jPanelGradient3 = new jpanelgradient.JPanelGradient();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanelGradient4 = new jpanelgradient.JPanelGradient();
        jLabel26 = new javax.swing.JLabel();
        jPanelGradient5 = new jpanelgradient.JPanelGradient();
        jLabel28 = new javax.swing.JLabel();
        jPanelGradient6 = new jpanelgradient.JPanelGradient();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        jScrollPane2.setBackground(new java.awt.Color(153, 255, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanelGradient1.setColorStart(new java.awt.Color(0, 204, 204));
        jPanelGradient1.setColotEnd(new java.awt.Color(255, 51, 255));
        jPanelGradient1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Menu Paket Hemat");
        jPanelGradient1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Menu Makanan");
        jPanelGradient1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Menu Minuman");
        jPanelGradient1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        totalPK.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalPK.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        totalPK.setText("jLabel5");
        jPanelGradient1.add(totalPK, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        totalM.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalM.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        totalM.setText("jLabel5");
        jPanelGradient1.add(totalM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        totalMN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalMN.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        totalMN.setText("jLabel5");
        jPanelGradient1.add(totalMN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bc.png"))); // NOI18N
        jPanelGradient1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 140, 140));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Instagram");
        jPanelGradient1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hk.png"))); // NOI18N
        jPanelGradient1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jPanelGradient2.setColorStart(new java.awt.Color(0, 204, 204));
        jPanelGradient2.setColotEnd(new java.awt.Color(204, 255, 153));
        jPanelGradient2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ag.png"))); // NOI18N
        jPanelGradient2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jPanelGradient3.setColorStart(new java.awt.Color(153, 204, 255));
        jPanelGradient3.setColotEnd(new java.awt.Color(255, 255, 102));
        jPanelGradient3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("warungambyar2021");
        jPanelGradient3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sb.png"))); // NOI18N
        jPanelGradient3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jPanelGradient4.setColorStart(new java.awt.Color(153, 204, 255));
        jPanelGradient4.setColotEnd(new java.awt.Color(255, 255, 102));
        jPanelGradient4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/mb.png"))); // NOI18N
        jPanelGradient4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jPanelGradient5.setColorStart(new java.awt.Color(153, 204, 255));
        jPanelGradient5.setColotEnd(new java.awt.Color(255, 255, 102));
        jPanelGradient5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bs.png"))); // NOI18N
        jPanelGradient5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 640));

        jPanelGradient6.setColorStart(new java.awt.Color(153, 204, 255));
        jPanelGradient6.setColotEnd(new java.awt.Color(255, 255, 102));
        jPanelGradient6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("warungambyar2021");
        jPanelGradient6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ng.png"))); // NOI18N
        jPanelGradient6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 640));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGradient2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGradient3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGradient4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGradient5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGradient6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelGradient5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelGradient6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(551, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3364, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private jpanelgradient.JPanelGradient jPanelGradient1;
    private jpanelgradient.JPanelGradient jPanelGradient2;
    private jpanelgradient.JPanelGradient jPanelGradient3;
    private jpanelgradient.JPanelGradient jPanelGradient4;
    private jpanelgradient.JPanelGradient jPanelGradient5;
    private jpanelgradient.JPanelGradient jPanelGradient6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel totalM;
    private javax.swing.JLabel totalMN;
    private javax.swing.JLabel totalPK;
    // End of variables declaration//GEN-END:variables
}
