/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasirpro;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author M. Aziz Ridwan
 */
public class Main extends javax.swing.JFrame {
    

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDashboard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bDashboard = new javax.swing.JLabel();
        pConten = new jpanelgradient.JPanelGradient();
        jLabel10 = new javax.swing.JLabel();
        pMakanan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bMakanan = new javax.swing.JLabel();
        pMinuman = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bMinuman = new javax.swing.JLabel();
        pPaket = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bPaket = new javax.swing.JLabel();
        pKasir = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bKasir = new javax.swing.JLabel();
        pAbout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bAbout = new javax.swing.JLabel();
        pLogout = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        bLogout = new javax.swing.JLabel();
        cDashboard = new javax.swing.JPanel();
        cMakanan = new javax.swing.JPanel();
        cMinuman = new javax.swing.JPanel();
        cPaket = new javax.swing.JPanel();
        cTransaksi = new javax.swing.JPanel();
        cAbout = new javax.swing.JPanel();
        cLogout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pDashboard.setBackground(new java.awt.Color(239, 175, 139));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dashboard (1).png"))); // NOI18N

        bDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bDashboard.setForeground(new java.awt.Color(0, 102, 102));
        bDashboard.setText("Dashboard");
        bDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bDashboardMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pDashboardLayout = new javax.swing.GroupLayout(pDashboard);
        pDashboard.setLayout(pDashboardLayout);
        pDashboardLayout.setHorizontalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(bDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pDashboardLayout.setVerticalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(bDashboard))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(pDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, 50));

        pConten.setColorStart(new java.awt.Color(204, 204, 255));
        pConten.setColotEnd(new java.awt.Color(204, 255, 0));
        pConten.setLayout(new java.awt.BorderLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bd (1).png"))); // NOI18N
        pConten.add(jLabel10, java.awt.BorderLayout.CENTER);

        getContentPane().add(pConten, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 1040, 620));

        pMakanan.setBackground(new java.awt.Color(239, 175, 139));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bibimbap (1).png"))); // NOI18N

        bMakanan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bMakanan.setForeground(new java.awt.Color(0, 102, 102));
        bMakanan.setText("Data Makanan");
        bMakanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bMakananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMakananMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bMakananMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pMakananLayout = new javax.swing.GroupLayout(pMakanan);
        pMakanan.setLayout(pMakananLayout);
        pMakananLayout.setHorizontalGroup(
            pMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMakananLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(bMakanan)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pMakananLayout.setVerticalGroup(
            pMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMakananLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMakanan)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        getContentPane().add(pMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, 50));

        pMinuman.setBackground(new java.awt.Color(239, 175, 139));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/drink (1).png"))); // NOI18N

        bMinuman.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bMinuman.setForeground(new java.awt.Color(0, 102, 102));
        bMinuman.setText("Data Minuman");
        bMinuman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bMinumanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMinumanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bMinumanMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pMinumanLayout = new javax.swing.GroupLayout(pMinuman);
        pMinuman.setLayout(pMinumanLayout);
        pMinumanLayout.setHorizontalGroup(
            pMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMinumanLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(bMinuman)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pMinumanLayout.setVerticalGroup(
            pMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMinumanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMinuman)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 210, 50));

        pPaket.setBackground(new java.awt.Color(239, 175, 139));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/fast-food (1).png"))); // NOI18N

        bPaket.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bPaket.setForeground(new java.awt.Color(0, 102, 102));
        bPaket.setText("Paket Hemat");
        bPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bPaketMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bPaketMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pPaketLayout = new javax.swing.GroupLayout(pPaket);
        pPaket.setLayout(pPaketLayout);
        pPaketLayout.setHorizontalGroup(
            pPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPaketLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(bPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pPaketLayout.setVerticalGroup(
            pPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPaketLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bPaket)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        getContentPane().add(pPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 210, 50));

        pKasir.setBackground(new java.awt.Color(239, 175, 139));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cash-counter (1).png"))); // NOI18N

        bKasir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bKasir.setForeground(new java.awt.Color(0, 102, 102));
        bKasir.setText("Transaksi");
        bKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bKasirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bKasirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bKasirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pKasirLayout = new javax.swing.GroupLayout(pKasir);
        pKasir.setLayout(pKasirLayout);
        pKasirLayout.setHorizontalGroup(
            pKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKasirLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(bKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pKasirLayout.setVerticalGroup(
            pKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKasirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bKasir)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 210, 50));

        pAbout.setBackground(new java.awt.Color(239, 175, 139));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/information (1).png"))); // NOI18N

        bAbout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bAbout.setForeground(new java.awt.Color(0, 102, 102));
        bAbout.setText("About");
        bAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bAboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bAboutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pAboutLayout = new javax.swing.GroupLayout(pAbout);
        pAbout.setLayout(pAboutLayout);
        pAboutLayout.setHorizontalGroup(
            pAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAboutLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(bAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        pAboutLayout.setVerticalGroup(
            pAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAbout)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 210, 50));

        pLogout.setBackground(new java.awt.Color(239, 175, 139));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout (1) (1).png"))); // NOI18N

        bLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bLogout.setForeground(new java.awt.Color(0, 102, 102));
        bLogout.setText("Logout");
        bLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bLogoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pLogoutLayout = new javax.swing.GroupLayout(pLogout);
        pLogout.setLayout(pLogoutLayout);
        pLogoutLayout.setHorizontalGroup(
            pLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLogoutLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(bLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        pLogoutLayout.setVerticalGroup(
            pLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLogoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bLogout)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        getContentPane().add(pLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 210, 50));

        cDashboard.setBackground(new java.awt.Color(239, 175, 139));

        javax.swing.GroupLayout cDashboardLayout = new javax.swing.GroupLayout(cDashboard);
        cDashboard.setLayout(cDashboardLayout);
        cDashboardLayout.setHorizontalGroup(
            cDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        cDashboardLayout.setVerticalGroup(
            cDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(cDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        cMakanan.setBackground(new java.awt.Color(239, 175, 139));

        javax.swing.GroupLayout cMakananLayout = new javax.swing.GroupLayout(cMakanan);
        cMakanan.setLayout(cMakananLayout);
        cMakananLayout.setHorizontalGroup(
            cMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        cMakananLayout.setVerticalGroup(
            cMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(cMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        cMinuman.setBackground(new java.awt.Color(239, 175, 139));

        javax.swing.GroupLayout cMinumanLayout = new javax.swing.GroupLayout(cMinuman);
        cMinuman.setLayout(cMinumanLayout);
        cMinumanLayout.setHorizontalGroup(
            cMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        cMinumanLayout.setVerticalGroup(
            cMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(cMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        cPaket.setBackground(new java.awt.Color(239, 175, 139));

        javax.swing.GroupLayout cPaketLayout = new javax.swing.GroupLayout(cPaket);
        cPaket.setLayout(cPaketLayout);
        cPaketLayout.setHorizontalGroup(
            cPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        cPaketLayout.setVerticalGroup(
            cPaketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(cPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        cTransaksi.setBackground(new java.awt.Color(239, 175, 139));

        javax.swing.GroupLayout cTransaksiLayout = new javax.swing.GroupLayout(cTransaksi);
        cTransaksi.setLayout(cTransaksiLayout);
        cTransaksiLayout.setHorizontalGroup(
            cTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        cTransaksiLayout.setVerticalGroup(
            cTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(cTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        cAbout.setBackground(new java.awt.Color(239, 175, 139));

        javax.swing.GroupLayout cAboutLayout = new javax.swing.GroupLayout(cAbout);
        cAbout.setLayout(cAboutLayout);
        cAboutLayout.setHorizontalGroup(
            cAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        cAboutLayout.setVerticalGroup(
            cAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(cAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));

        cLogout.setBackground(new java.awt.Color(239, 175, 139));

        javax.swing.GroupLayout cLogoutLayout = new javax.swing.GroupLayout(cLogout);
        cLogout.setLayout(cLogoutLayout);
        cLogoutLayout.setHorizontalGroup(
            cLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        cLogoutLayout.setVerticalGroup(
            cLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(cLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/maink (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDashboardMouseEntered
        pDashboard.setBackground(new Color(219, 155, 119));
        cDashboard.setBackground(new Color(255, 255, 0));
    }//GEN-LAST:event_bDashboardMouseEntered

    private void bDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDashboardMouseExited
        pDashboard.setBackground(new Color(239, 175, 139));
        cDashboard.setBackground(new Color(239, 175, 139));
    }//GEN-LAST:event_bDashboardMouseExited

    private void bDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDashboardMousePressed
        pConten.removeAll();
        pConten.add(new Dashboard());
        pConten.repaint();
        pConten.revalidate();
        pDashboard.setBackground(new Color(173, 216, 230));
    }//GEN-LAST:event_bDashboardMousePressed

    private void bMakananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMakananMouseEntered
        pMakanan.setBackground(new Color(219, 155, 119));
        cMakanan.setBackground(new Color(255, 255, 0));
    }//GEN-LAST:event_bMakananMouseEntered

    private void bMakananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMakananMouseExited
        pMakanan.setBackground(new Color(239, 175, 139));
        cMakanan.setBackground(new Color(239, 175, 139));
    }//GEN-LAST:event_bMakananMouseExited

    private void bMakananMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMakananMousePressed
        pConten.removeAll();
        pConten.add(new Makanan());
        pConten.repaint();
        pConten.revalidate();
        pMakanan.setBackground(new Color(173, 216, 230));
    }//GEN-LAST:event_bMakananMousePressed

    private void bMinumanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMinumanMouseEntered
        pMinuman.setBackground(new Color(219, 155, 119));
        cMinuman.setBackground(new Color(255, 255, 0));
    }//GEN-LAST:event_bMinumanMouseEntered

    private void bMinumanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMinumanMouseExited
        pMinuman.setBackground(new Color(239, 175, 139));
        cMinuman.setBackground(new Color(239, 175, 139));
    }//GEN-LAST:event_bMinumanMouseExited

    private void bMinumanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMinumanMousePressed
        pConten.removeAll();
        pConten.add(new Minuman());
        pConten.repaint();
        pConten.revalidate();
        pMinuman.setBackground(new Color(173, 216, 230));
    }//GEN-LAST:event_bMinumanMousePressed

    private void bPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPaketMouseEntered
        pPaket.setBackground(new Color(219, 155, 119));
        cPaket.setBackground(new Color(255, 255, 0));
    }//GEN-LAST:event_bPaketMouseEntered

    private void bPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPaketMouseExited
        pPaket.setBackground(new Color(239, 175, 139));
        cPaket.setBackground(new Color(239, 175, 139));
    }//GEN-LAST:event_bPaketMouseExited

    private void bPaketMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPaketMousePressed
        pConten.removeAll();
        pConten.add(new Paket_Hemat());
        pConten.repaint();
        pConten.revalidate();
        pPaket.setBackground(new Color(173, 216, 230));
    }//GEN-LAST:event_bPaketMousePressed

    private void bKasirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKasirMouseEntered
        pKasir.setBackground(new Color(219, 155, 119));
        cTransaksi.setBackground(new Color(255, 255, 0));
    }//GEN-LAST:event_bKasirMouseEntered

    private void bKasirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKasirMouseExited
        pKasir.setBackground(new Color(239, 175, 139));
        cTransaksi.setBackground(new Color(239, 175, 139));
    }//GEN-LAST:event_bKasirMouseExited

    private void bKasirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKasirMousePressed
        pConten.removeAll();
        pConten.add(new Kasir());
        pConten.repaint();
        pConten.revalidate();
        pKasir.setBackground(new Color(173, 216, 230));
    }//GEN-LAST:event_bKasirMousePressed

    private void bAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAboutMouseEntered
        pAbout.setBackground(new Color(219, 155, 119));
        cAbout.setBackground(new Color(255, 255, 0));
    }//GEN-LAST:event_bAboutMouseEntered

    private void bAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAboutMouseExited
        pAbout.setBackground(new Color(239, 175, 139));
        cAbout.setBackground(new Color(239, 175, 139));
    }//GEN-LAST:event_bAboutMouseExited

    private void bAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAboutMousePressed
        pConten.removeAll();
        pConten.add(new About());
        pConten.repaint();
        pConten.revalidate();
        pAbout.setBackground(new Color(173, 216, 230));
    }//GEN-LAST:event_bAboutMousePressed

    private void bLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseEntered
        pLogout.setBackground(new Color(219, 155, 119));
        cLogout.setBackground(new Color(255, 255, 0));
    }//GEN-LAST:event_bLogoutMouseEntered

    private void bLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseExited
        pLogout.setBackground(new Color(239, 175, 139));
        cLogout.setBackground(new Color(239, 175, 139));
    }//GEN-LAST:event_bLogoutMouseExited

    private void bLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMousePressed
         new warning().setVisible(true);
    
    // Mengubah warna background pLogout
    pLogout.setBackground(new Color(173, 216, 230));

    
    }//GEN-LAST:event_bLogoutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
            UIManager.put("Button.arc", 15);
            UIManager.put("TextComponent.arc", 15);
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bAbout;
    private javax.swing.JLabel bDashboard;
    private javax.swing.JLabel bKasir;
    private javax.swing.JLabel bLogout;
    private javax.swing.JLabel bMakanan;
    private javax.swing.JLabel bMinuman;
    private javax.swing.JLabel bPaket;
    private javax.swing.JPanel cAbout;
    private javax.swing.JPanel cDashboard;
    private javax.swing.JPanel cLogout;
    private javax.swing.JPanel cMakanan;
    private javax.swing.JPanel cMinuman;
    private javax.swing.JPanel cPaket;
    private javax.swing.JPanel cTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pAbout;
    private jpanelgradient.JPanelGradient pConten;
    private javax.swing.JPanel pDashboard;
    private javax.swing.JPanel pKasir;
    private javax.swing.JPanel pLogout;
    private javax.swing.JPanel pMakanan;
    private javax.swing.JPanel pMinuman;
    private javax.swing.JPanel pPaket;
    // End of variables declaration//GEN-END:variables
}
